AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
    Serverless application to stream events from AWS CloudWatch Logs to Splunk HTTP Event Collector (HEC).

    This SAM template creates the Lambda function with its IAM execution role, a CloudWatch Logs subscription
    filter for user-provided log group, along with a Lambda permission to grant CloudWatch Logs permission
    to invoke this function. Log group must be in same region as the region where this stack is created.

    Last Modified: 06 Oct, 2017
    Authors: Roy Arsan <roy@splunk.com>, Tarik Makota <tmak@amazon.com>

Parameters:
    CloudWatchLogsGroupName: 
      Type: "String"
      Description: "Name of a CloudWatch log group (must be in the same region)"

    SplunkHttpEventCollectorURL:
      Type: "String"
      Description: "URL address of your Splunk HTTP event collector endpoint"

    SplunkHttpEventCollectorToken:
      Type: "String"
      Description: "Token of your Splunk HTTP event collector endpoint"

Outputs:
    SplunkCloudWatchLogsProcessorFunction:
      Description: "Splunk CloudWatch Logs Lambda Function ARN"
      Value: !GetAtt SplunkCloudWatchLogsProcessorFunction.Arn

Resources:
    CloudWatchLogsSubscriptionFilter:
      Type: "AWS::Logs::SubscriptionFilter"
      DependsOn: CloudWatchLogsLambdaPermission
      Properties:
        DestinationArn: !GetAtt SplunkCloudWatchLogsProcessorFunction.Arn
        LogGroupName: !Ref CloudWatchLogsGroupName
        FilterPattern: ""

    CloudWatchLogsLambdaPermission:
      Type: "AWS::Lambda::Permission"
      Properties: 
        Action: "lambda:InvokeFunction"
        FunctionName: !GetAtt SplunkCloudWatchLogsProcessorFunction.Arn
        Principal: !Join
          - "."
          - [ "logs", !Ref "AWS::Region", !Ref "AWS::URLSuffix" ]
        SourceAccount: !Ref "AWS::AccountId"
        SourceArn: !Join
          - ":"
          - [ "arn", !Ref "AWS::Partition", "logs", !Ref "AWS::Region", !Ref "AWS::AccountId", "log-group", !Ref CloudWatchLogsGroupName, "*" ]

    SplunkCloudWatchLogsProcessorFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs8.10
        CodeUri: ./splunk-cloudwatch-logs-processor.zip
        Description: Stream events from AWS CloudWatch Logs to Splunk HTTP event collector
        MemorySize: 512
        Timeout: 30
        Environment:
          Variables:
            SPLUNK_HEC_URL: !Ref SplunkHttpEventCollectorURL
            SPLUNK_HEC_TOKEN: !Ref SplunkHttpEventCollectorToken

  