AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
    Serverless application to stream events from AWS Kinesis to Splunk HTTP Event Collector (HEC).

    This SAM template creates the Lambda function with its IAM execution role and the event source mapping to Kinesis stream.
    Kinesis Stream must be in same region as the region where this stack is created.

    Last Modified: 29 Nov, 2017
    Authors: Roy Arsan <roy@splunk.com>, Tarik Makota <tmak@amazon.com>

Parameters:
    KinesisStreamName: 
      Type: "String"
      Description: "Name of a Kinesis stream (must be in the same region). The Lambda function will be invoked whenever this stream is updated."
    
    KinesisStreamBatchSize:
      Type: "Number"
      Description: "The largest number of records that AWS Lambda will retrieve from your stream at the time of invoking your function. Your function receives an event with all the retrieved records."
      Default: "100"

    KinesisStreamStartingPosition:
      Type: "String"
      Description: "The position in the stream where AWS Lambda should start reading. Allowed values are 'AT_TIMESTAMP', 'TRIM_HORIZON', 'LATEST'. For more information, see ShardIteratorType in the Amazon Kinesis API Reference."
      Default: "LATEST" 

    SplunkHttpEventCollectorURL:
      Type: "String"
      Description: "URL address of your Splunk HTTP event collector endpoint"

    SplunkHttpEventCollectorToken:
      Type: "String"
      Description: "Token of your Splunk HTTP event collector endpoint"
      
Outputs:
    SplunkKinesisStreamProcessor:
      Description: "Splunk Kinesis Stream Lambda Function ARN"
      Value: !GetAtt SplunkKinesisStreamProcessor.Arn

Resources:
    SplunkKinesisStreamProcessor:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs8.10
        CodeUri: ./splunk-kinesis-stream-processor.zip
        Policies:
          - KinesisStreamReadPolicy:
              StreamName: !Ref KinesisStreamName
        Description: Stream events from AWS Kinesis Stream to Splunk HTTP event collector
        MemorySize: 512
        Timeout: 10
        Environment:
          Variables:
            SPLUNK_HEC_URL: !Ref SplunkHttpEventCollectorURL
            SPLUNK_HEC_TOKEN: !Ref SplunkHttpEventCollectorToken
        Events:
          KinesisStream:
            Type: Kinesis
            Properties:
              Stream: !Join [ "", [ "arn:", !Ref "AWS::Partition", ":kinesis:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":stream/", !Ref KinesisStreamName ] ]
              StartingPosition: !Ref KinesisStreamStartingPosition
              BatchSize: !Ref KinesisStreamBatchSize

  